const $=id=>document.getElementById(id);let config=null,scripts=[],timer=null;
async function api(path,options={}){const response=await fetch(path,{headers:{"Content-Type":"application/json",...(options.headers||{})},...options});let body={};try{body=await response.json()}catch{}if(!response.ok)throw new Error(body.detail||`HTTP ${response.status}`);return body}
function notice(message,error=false){const el=$("notice");el.textContent=message;el.className=error?"error":"";el.style.display="block";clearTimeout(notice.timeout);notice.timeout=setTimeout(()=>el.style.display="none",6000)}
function escapeHtml(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function scriptOptions(selected=""){return `<option value="">Selecione...</option>`+scripts.map(s=>`<option value="${escapeHtml(s.reference)}" ${s.reference===selected?"selected":""}>${escapeHtml(s.name)} — ${escapeHtml(s.directory_label)}</option>`).join("")}
function renderMenu(){const rows=config.menu.map((item,index)=>`<div class="menu-row" data-index="${index}"><div class="slot">${index+1}</div><label class="enable"><input class="enabled" type="checkbox" ${item.enabled?"checked":""}></label><label>Nome<input class="name" maxlength="30" value="${escapeHtml(item.name)}"></label><label>Tipo<select class="kind"><option value="command" ${item.kind==="command"?"selected":""}>Comando</option><option value="python" ${item.kind==="python"?"selected":""}>Python</option></select></label><label class="target command-cell">Comando<input class="command" value="${escapeHtml(item.command)}"></label><label class="script-cell ${item.kind==="python"?"":"hidden"}">Script<select class="script">${scriptOptions(item.script)}</select></label><label class="shell-cell ${item.kind==="command"?"":"hidden"}">Terminal<select class="shell">${["auto","cmd","powershell","sh"].map(x=>`<option ${item.shell===x?"selected":""}>${x}</option>`).join("")}</select></label><label>Timeout<input class="timeout" type="number" min="1" max="3600" value="${item.timeout_sec}"></label><button class="run secondary">Executar</button></div>`).join("");$("menuRows").innerHTML=rows;document.querySelectorAll(".menu-row").forEach(row=>{row.querySelector(".kind").onchange=()=>toggleRow(row);row.querySelector(".run").onclick=()=>runSlot(+row.dataset.index)})}
function toggleRow(row){const py=row.querySelector(".kind").value==="python";row.querySelector(".command-cell").classList.toggle("hidden",py);row.querySelector(".script-cell").classList.toggle("hidden",!py);row.querySelector(".shell-cell").classList.toggle("hidden",py)}
function readConfig(){config.menu=[...document.querySelectorAll(".menu-row")].map(row=>({enabled:row.querySelector(".enabled").checked,name:row.querySelector(".name").value,kind:row.querySelector(".kind").value,command:row.querySelector(".command").value,script:row.querySelector(".script").value,shell:row.querySelector(".shell").value,timeout_sec:+row.querySelector(".timeout").value}));return config}
function renderConfig(){renderMenu()}
async function loadScripts(){if(config&&document.querySelectorAll(".menu-row").length)readConfig();const data=await api("/api/scripts");scripts=data.scripts;$("directories").innerHTML=data.directories.map(d=>`<div class="directory"><div><strong>${escapeHtml(d.label)}</strong><br><small>${escapeHtml(d.path)} · ${d.script_count} script(s)${d.available?"":" · indisponivel"}</small></div>${d.managed?"":`<button class="danger remove-dir" data-id="${escapeHtml(d.id)}">Remover</button>`}</div>`).join("");document.querySelectorAll(".remove-dir").forEach(b=>b.onclick=async()=>{try{await api(`/api/script-directories/${encodeURIComponent(b.dataset.id)}`,{method:"DELETE"});await loadScripts();renderConfig()}catch(e){notice(e.message,true)}});if(config)renderConfig()}
async function refreshStatus(){try{const data=await api("/api/status");const c=data.connection;$("statusDot").classList.toggle("online",c.connected);$("statusText").textContent=c.connected?`Modulo conectado · ${c.port}`:(c.state==="connecting"?"Procurando modulo...":"Aguardando modulo...");const e=data.execution;$("currentExecution").textContent=e.state==="idle"?"Nenhuma execucao registrada.":`${e.state.toUpperCase()} · ${e.name||e.target||"acao"}${e.motor_stop?` · parada: ${e.motor_stop.state}`:""}`;if(c.error&&!c.connected)$("currentExecution").textContent+=` · conexao automatica: ${c.error}`}catch(e){$("statusText").textContent="Servico indisponivel"}}
function logCard(entry,type){const state=entry.state||entry.kind||"log";const date=new Date((entry.finished_at||entry.timestamp||entry.started_at||0)*1000).toLocaleString();const details=[];if(entry.command)details.push(`Comando: ${entry.command}`);if(entry.target)details.push(`Alvo: ${entry.target}`);if(entry.response)details.push(`Resposta: ${entry.response}`);if(entry.returncode!==undefined)details.push(`Retorno: ${entry.returncode}`);if(entry.error)details.push(`Erro: ${entry.error}`);if(entry.stdout)details.push(`stdout:\n${entry.stdout}`);if(entry.stderr)details.push(`stderr:\n${entry.stderr}`);if(entry.motor_stop)details.push(`Parada dos motores: ${entry.motor_stop.state}${entry.motor_stop.error?` — ${entry.motor_stop.error}`:""}${entry.motor_stop.stdout?`\n${entry.motor_stop.stdout}`:""}${entry.motor_stop.stderr?`\n${entry.motor_stop.stderr}`:""}`);return `<article class="log ${escapeHtml(state)}"><div class="log-head"><strong>${escapeHtml(type)} · ${escapeHtml(state)}</strong><small>${escapeHtml(date)}</small></div>${details.length?`<pre>${escapeHtml(details.join("\n"))}</pre>`:""}</article>`}
async function loadLogs(){try{const [executions,activity]=await Promise.all([api("/api/executions?limit=100"),api("/api/activity?limit=150")]);const mixed=[...executions.entries.map(x=>({...x,_type:"Execucao",_time:x.finished_at||x.started_at||0})),...activity.entries.map(x=>({...x,_type:"Modulo",_time:x.timestamp||0}))].sort((a,b)=>b._time-a._time);$("logs").innerHTML=mixed.length?mixed.map(x=>logCard(x,x._type)).join(""):"<p>Nenhum registro.</p>"}catch{}}
async function runSlot(slot){try{readConfig();await api("/api/config",{method:"PUT",body:JSON.stringify(config)});await api(`/api/executions/menu/${slot}`,{method:"POST",body:"{}"});notice("Execucao iniciada.");await refreshStatus()}catch(e){notice(e.message,true)}}
async function init(){try{config=await api("/api/config");await loadScripts();renderConfig();await Promise.all([refreshStatus(),loadLogs()]);timer=setInterval(()=>{refreshStatus();loadLogs()},1500)}catch(e){notice(e.message,true)}}
$("saveConfig").onclick=async()=>{try{const result=await api("/api/config",{method:"PUT",body:JSON.stringify(readConfig())});config=result.config;notice(result.warning||"Configuracao salva e sincronizada.")}catch(e){notice(e.message,true)}};
$("selectDirectory").onclick=async()=>{try{const result=await api("/api/script-directories/select",{method:"POST",body:"{}"});if(result.path)$("directoryPath").value=result.path}catch(e){notice(e.message,true)}};$("addDirectory").onclick=async()=>{try{await api("/api/script-directories",{method:"POST",body:JSON.stringify({path:$("directoryPath").value})});$("directoryPath").value="";await loadScripts();notice("Diretorio adicionado.")}catch(e){notice(e.message,true)}};$("uploadScript").onclick=async()=>{const file=$("scriptFile").files[0];if(!file)return notice("Selecione um arquivo .py.",true);try{await api("/api/scripts",{method:"POST",body:JSON.stringify({filename:file.name,content:await file.text()})});await loadScripts();notice("Script enviado.")}catch(e){notice(e.message,true)}};
$("runCommand").onclick=async()=>{try{await api("/api/executions/command",{method:"POST",body:JSON.stringify({kind:"command",command:$("manualCommand").value,shell:$("manualShell").value,timeout_sec:30})});notice("Comando iniciado.")}catch(e){notice(e.message,true)}};$("stopExecution").onclick=()=>api("/api/executions/stop",{method:"POST",body:"{}"}).catch(e=>notice(e.message,true));
$("clearLogs").onclick=async()=>{await Promise.all([api("/api/executions",{method:"DELETE"}),api("/api/activity",{method:"DELETE"})]);await loadLogs()};init();
